----------------------------------------------------------------------------------------
-- TABLA PARA GUARDAR INFORMACIÓN DE TRANSFORMADORES CON SU CORRESPONDIENTE CÓDIGO DANE
----------------------------------------------------------------------------------------
CREATE TABLE TRAFO_DANE(
    IDENTIFICADOR_EMPRESA NUMBER(5,0),
    COD_TRAFO VARCHAR2(50 BYTE),
    COD_DANE VARCHAR2(8 BYTE)
);

----------------------------------------------------------------------------------------
-- INSERT TABLA 'TRAFO_DANE'
----------------------------------------------------------------------------------------
INSERT INTO TRAFO_DANE -- 2.109.954.653  Filas
SELECT DISTINCT F1.IDENTIFICADOR_EMPRESA, F1.CAR_T438_COD_CONEX, F23.DANE FROM
(
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T438_NIU,
        CAR_T438_COD_CONEX
    FROM
        CARG_COMERCIAL_E.CAR_T438_FORMATO1
    WHERE  
        CAR_T438_TIPO_CONEX = 'T'
        AND CAR_CARG_ANO = 2019
) F1,
(
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T439_NIU NIU,
        CAR_T439_DANE DANE
    FROM
        CARG_COMERCIAL_E.CAR_T439_FORMATO2
    WHERE
        CAR_CARG_ANO = 2019
    UNION ALL
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T440_NIU NIU,
        CAR_T440_DANE DANE
    FROM
        CARG_COMERCIAL_E.CAR_T440_FORMATO3
    WHERE
        CAR_CARG_ANO = 2019
) F23
WHERE
    F1.CAR_T438_NIU = NIU
    AND F1.IDENTIFICADOR_EMPRESA = F23.IDENTIFICADOR_EMPRESA;

----------------------------------------------------------------------------------------
-- SCRIPT PARA UNIR F5 CON SU RESPECTIVO CODIGO DANE
----------------------------------------------------------------------------------------
SELECT * FROM
(
    SELECT * FROM TRAFO_DANE
) TRAFODANE,
(
    SELECT
        CAR_T442_COD_TRANS,
        CAR_T442_LONG,
        CAR_T442_LAT,
        IDENTIFICADOR_EMPRESA
    FROM
        CARG_COMERCIAL_E.CAR_T442_FORMATO5
    WHERE
        IDENTIFICADOR_EMPRESA = 2249
        AND CAR_CARG_ANO = 2019
) F5
WHERE
    TRAFODANE.COD_TRAFO = F5.CAR_T442_COD_TRANS
    AND TRAFODANE.IDENTIFICADOR_EMPRESA = F5.IDENTIFICADOR_EMPRESA;

----------------------------------------------------------------------------------------
-- SCRIPT PARA OBTENER POR CODIGO DANE LA CANTIDAD DE MINUTOS DE INTERRUPCIÓN DE CADA UNA DE LAS CAUSAS
-- SE OBTIENE TAMBIEN EL TOTAL DE MINUTOS DE INTERRUPCION DE TODAS LAS CAUSAS POR CODIGO DANE
-- SE MUESTRA LATITUD Y LONGITUD DEL CENTRO POBLADO (CODIGO DANE)
----------------------------------------------------------------------------------------
SELECT
    CP.NOMBRE_CENTRO_POBLADO,
    CP.LONGITUD,
    CP.LATITUD,
    DANE_INTER.*
FROM
(
    SELECT
        INTER.*,
        PNEXC+NPNEXC+REMER+STNSTR+SEGCIU+FNIVEL1+CASTNAT+TERR+CALZESP+TSUBEST+INFRA+SUMI+PEXP AS TOTAL_INTER
    FROM
    (
        SELECT
            TRAFODANE.COD_DANE,
            F5.IDENTIFICADOR_EMPRESA,
            CASE WHEN (:PNEXC = 16) THEN SUM(F5.CAR_T442_MIN_PBEXC) ELSE 0 END AS PNEXC,
            CASE WHEN (:NPNEXC = 18) THEN SUM(F5.CAR_T442_MIN_NPNEXC) ELSE 0 END AS NPNEXC,
            CASE WHEN (:REMER = 20) THEN SUM(F5.CAR_T442_MIN_REMER) ELSE 0 END AS REMER,
            CASE WHEN (:STNSTR = 22) THEN SUM(F5.CAR_T442_MIN_STNSTR) ELSE 0 END AS STNSTR,
            CASE WHEN (:SEGCIU = 24) THEN SUM(F5.CAR_T442_MIN_SEG_CIU) ELSE 0 END AS SEGCIU,
            CASE WHEN (:FNIVEL1 = 26) THEN SUM(F5.CAR_T442_MIN_FNIVEL1) ELSE 0 END AS FNIVEL1,
            CASE WHEN (:CASTNAT = 28) THEN SUM(F5.CAR_T442_MIN_CASTNAT) ELSE 0 END AS CASTNAT,
            CASE WHEN (:TERR = 30) THEN SUM(F5.CAR_T442_MIN_TERR) ELSE 0 END AS TERR,
            CASE WHEN (:CALZESP = 32) THEN SUM(F5.CAR_T442_MIN_CAL_ZESP) ELSE 0 END AS CALZESP,
            CASE WHEN (:TSUBEST = 34) THEN SUM(F5.CAR_T442_MIN_TSUBEST) ELSE 0 END AS TSUBEST,
            CASE WHEN (:INFRA = 36) THEN SUM(F5.CAR_T442_MIN_INFRA) ELSE 0 END AS INFRA,
            CASE WHEN (:SUMI = 38) THEN SUM(F5.CAR_T442_MIN_SUMI) ELSE 0 END AS SUMI,
            CASE WHEN (:PEXP = 40) THEN SUM(F5.CAR_T442_MIN_EXP) ELSE 0 END AS PEXP
        FROM
        (
            SELECT
                *
            FROM
                CARG_COMERCIAL_E.CAR_T442_FORMATO5
            WHERE
                CAR_CARG_ANO = :ANIO_ARG
                AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
                AND (CAR_CARG_MES = :MES_ARG OR :MES_ARG = 0 )
        ) F5,
        (SELECT * FROM TRAFO_DANE) TRAFODANE
        WHERE
            F5.CAR_T442_COD_TRANS = TRAFODANE.COD_TRAFO
            AND F5.IDENTIFICADOR_EMPRESA = TRAFODANE.IDENTIFICADOR_EMPRESA
        GROUP BY
            TRAFODANE.COD_DANE,
            F5.IDENTIFICADOR_EMPRESA
    ) INTER
    WHERE PNEXC+NPNEXC+REMER+STNSTR+SEGCIU+FNIVEL1+CASTNAT+TERR+CALZESP+TSUBEST+INFRA+SUMI+PEXP > 0
) DANE_INTER,
(SELECT * FROM JHERRERAA.GIS_CENTRO_POBLADO) CP
WHERE DANE_INTER.COD_DANE = CP.CODIGO_CENTRO_POBLADO;