CREATE TABLE TRAFO_DANE(
    IDENTIFICADOR_EMPRESA NUMBER(5,0),
    COD_TRAFO VARCHAR2(50 BYTE),
    COD_DANE VARCHAR2(8 BYTE)
);

INSERT INTO TRAFO_DANE -- 2.109.954.653  Filas
SELECT DISTINCT F1.IDENTIFICADOR_EMPRESA, F1.CAR_T438_COD_CONEX, F23.DANE FROM
(
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T438_NIU,
        CAR_T438_COD_CONEX
    FROM
        CARG_COMERCIAL_E.CAR_T438_FORMATO1
    WHERE  
        CAR_T438_TIPO_CONEX = 'T'
        AND CAR_CARG_ANO = 2019
) F1,
(
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T439_NIU NIU,
        CAR_T439_DANE DANE
    FROM
        CARG_COMERCIAL_E.CAR_T439_FORMATO2
    WHERE
        CAR_CARG_ANO = 2019
    UNION ALL
    SELECT
        IDENTIFICADOR_EMPRESA,
        CAR_T440_NIU NIU,
        CAR_T440_DANE DANE
    FROM
        CARG_COMERCIAL_E.CAR_T440_FORMATO3
    WHERE
        CAR_CARG_ANO = 2019
) F23
WHERE
    F1.CAR_T438_NIU = NIU
    AND F1.IDENTIFICADOR_EMPRESA = F23.IDENTIFICADOR_EMPRESA;




SELECT * FROM
(
    SELECT * FROM TRAFO_DANE
) TD,
(
    SELECT
        CAR_T442_COD_TRANS,
        CAR_T442_LONG,
        CAR_T442_LAT,
        IDENTIFICADOR_EMPRESA
    FROM
        CARG_COMERCIAL_E.CAR_T442_FORMATO5
    WHERE
        IDENTIFICADOR_EMPRESA = 2249
        AND CAR_CARG_ANO = 2019
) F5
WHERE
    TD.COD_TRAFO = F5.CAR_T442_COD_TRANS
    AND TD.IDENTIFICADOR_EMPRESA = F5.IDENTIFICADOR_EMPRESA;